server:
  port: 8085
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/memposit-google-oauth2?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
